// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: service/grpc/creature.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Representa um snapshot básico de uma criatura no mundo
type CreatureSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	X             float32                `protobuf:"fixed32,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,5,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,6,opt,name=z,proto3" json:"z,omitempty"`
	Hp            float32                `protobuf:"fixed32,7,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         float32                `protobuf:"fixed32,8,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Animation     string                 `protobuf:"bytes,9,opt,name=animation,proto3" json:"animation,omitempty"`
	State         string                 `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Timestamp     int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Yaw           float32                `protobuf:"fixed32,12,opt,name=yaw,proto3" json:"yaw,omitempty"` // 👈 ADICIONADO AQUI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatureSnapshot) Reset() {
	*x = CreatureSnapshot{}
	mi := &file_service_grpc_creature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatureSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatureSnapshot) ProtoMessage() {}

func (x *CreatureSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_service_grpc_creature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatureSnapshot.ProtoReflect.Descriptor instead.
func (*CreatureSnapshot) Descriptor() ([]byte, []int) {
	return file_service_grpc_creature_proto_rawDescGZIP(), []int{0}
}

func (x *CreatureSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatureSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatureSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreatureSnapshot) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CreatureSnapshot) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CreatureSnapshot) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *CreatureSnapshot) GetHp() float32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CreatureSnapshot) GetMaxHp() float32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *CreatureSnapshot) GetAnimation() string {
	if x != nil {
		return x.Animation
	}
	return ""
}

func (x *CreatureSnapshot) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreatureSnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CreatureSnapshot) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

// Stream contínuo de snapshots
type SnapshotStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Campo reservado para filtragens futuras (ex: zona, facção, etc)
	Zone          string `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotStreamRequest) Reset() {
	*x = SnapshotStreamRequest{}
	mi := &file_service_grpc_creature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotStreamRequest) ProtoMessage() {}

func (x *SnapshotStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_grpc_creature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotStreamRequest.ProtoReflect.Descriptor instead.
func (*SnapshotStreamRequest) Descriptor() ([]byte, []int) {
	return file_service_grpc_creature_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotStreamRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

// Stream de várias criaturas por tick
type CreatureSnapshotBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*CreatureSnapshot    `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatureSnapshotBatch) Reset() {
	*x = CreatureSnapshotBatch{}
	mi := &file_service_grpc_creature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatureSnapshotBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatureSnapshotBatch) ProtoMessage() {}

func (x *CreatureSnapshotBatch) ProtoReflect() protoreflect.Message {
	mi := &file_service_grpc_creature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatureSnapshotBatch.ProtoReflect.Descriptor instead.
func (*CreatureSnapshotBatch) Descriptor() ([]byte, []int) {
	return file_service_grpc_creature_proto_rawDescGZIP(), []int{2}
}

func (x *CreatureSnapshotBatch) GetSnapshots() []*CreatureSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_service_grpc_creature_proto protoreflect.FileDescriptor

const file_service_grpc_creature_proto_rawDesc = "" +
	"\n" +
	"\x1bservice/grpc/creature.proto\x12\x04grpc\"\xff\x01\n" +
	"\x10CreatureSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\f\n" +
	"\x01x\x18\x04 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x06 \x01(\x02R\x01z\x12\x0e\n" +
	"\x02hp\x18\a \x01(\x02R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\b \x01(\x02R\x05maxHp\x12\x1c\n" +
	"\tanimation\x18\t \x01(\tR\tanimation\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03yaw\x18\f \x01(\x02R\x03yaw\"+\n" +
	"\x15SnapshotStreamRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\"M\n" +
	"\x15CreatureSnapshotBatch\x124\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x16.grpc.CreatureSnapshotR\tsnapshots2c\n" +
	"\fCreatureSync\x12S\n" +
	"\x15StreamCreatureUpdates\x12\x1b.grpc.SnapshotStreamRequest\x1a\x1b.grpc.CreatureSnapshotBatch0\x01B0Z.github.com/lunajones/apeiron/service/grpc;grpcb\x06proto3"

var (
	file_service_grpc_creature_proto_rawDescOnce sync.Once
	file_service_grpc_creature_proto_rawDescData []byte
)

func file_service_grpc_creature_proto_rawDescGZIP() []byte {
	file_service_grpc_creature_proto_rawDescOnce.Do(func() {
		file_service_grpc_creature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_grpc_creature_proto_rawDesc), len(file_service_grpc_creature_proto_rawDesc)))
	})
	return file_service_grpc_creature_proto_rawDescData
}

var file_service_grpc_creature_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_grpc_creature_proto_goTypes = []any{
	(*CreatureSnapshot)(nil),      // 0: grpc.CreatureSnapshot
	(*SnapshotStreamRequest)(nil), // 1: grpc.SnapshotStreamRequest
	(*CreatureSnapshotBatch)(nil), // 2: grpc.CreatureSnapshotBatch
}
var file_service_grpc_creature_proto_depIdxs = []int32{
	0, // 0: grpc.CreatureSnapshotBatch.snapshots:type_name -> grpc.CreatureSnapshot
	1, // 1: grpc.CreatureSync.StreamCreatureUpdates:input_type -> grpc.SnapshotStreamRequest
	2, // 2: grpc.CreatureSync.StreamCreatureUpdates:output_type -> grpc.CreatureSnapshotBatch
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_grpc_creature_proto_init() }
func file_service_grpc_creature_proto_init() {
	if File_service_grpc_creature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_grpc_creature_proto_rawDesc), len(file_service_grpc_creature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_grpc_creature_proto_goTypes,
		DependencyIndexes: file_service_grpc_creature_proto_depIdxs,
		MessageInfos:      file_service_grpc_creature_proto_msgTypes,
	}.Build()
	File_service_grpc_creature_proto = out.File
	file_service_grpc_creature_proto_goTypes = nil
	file_service_grpc_creature_proto_depIdxs = nil
}
