// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: service/grpc/creature.proto

package grpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreatureSync_StreamCreatureUpdates_FullMethodName = "/grpc.CreatureSync/StreamCreatureUpdates"
)

// CreatureSyncClient is the client API for CreatureSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreatureSyncClient interface {
	// Server-side streaming: apeiron envia snapshots contínuos
	StreamCreatureUpdates(ctx context.Context, in *SnapshotStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreatureSnapshotBatch], error)
}

type creatureSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewCreatureSyncClient(cc grpc.ClientConnInterface) CreatureSyncClient {
	return &creatureSyncClient{cc}
}

func (c *creatureSyncClient) StreamCreatureUpdates(ctx context.Context, in *SnapshotStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreatureSnapshotBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CreatureSync_ServiceDesc.Streams[0], CreatureSync_StreamCreatureUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotStreamRequest, CreatureSnapshotBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CreatureSync_StreamCreatureUpdatesClient = grpc.ServerStreamingClient[CreatureSnapshotBatch]

// CreatureSyncServer is the server API for CreatureSync service.
// All implementations must embed UnimplementedCreatureSyncServer
// for forward compatibility.
type CreatureSyncServer interface {
	// Server-side streaming: apeiron envia snapshots contínuos
	StreamCreatureUpdates(*SnapshotStreamRequest, grpc.ServerStreamingServer[CreatureSnapshotBatch]) error
	mustEmbedUnimplementedCreatureSyncServer()
}

// UnimplementedCreatureSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreatureSyncServer struct{}

func (UnimplementedCreatureSyncServer) StreamCreatureUpdates(*SnapshotStreamRequest, grpc.ServerStreamingServer[CreatureSnapshotBatch]) error {
	return status.Errorf(codes.Unimplemented, "method StreamCreatureUpdates not implemented")
}
func (UnimplementedCreatureSyncServer) mustEmbedUnimplementedCreatureSyncServer() {}
func (UnimplementedCreatureSyncServer) testEmbeddedByValue()                      {}

// UnsafeCreatureSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreatureSyncServer will
// result in compilation errors.
type UnsafeCreatureSyncServer interface {
	mustEmbedUnimplementedCreatureSyncServer()
}

func RegisterCreatureSyncServer(s grpc.ServiceRegistrar, srv CreatureSyncServer) {
	// If the following call pancis, it indicates UnimplementedCreatureSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreatureSync_ServiceDesc, srv)
}

func _CreatureSync_StreamCreatureUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CreatureSyncServer).StreamCreatureUpdates(m, &grpc.GenericServerStream[SnapshotStreamRequest, CreatureSnapshotBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CreatureSync_StreamCreatureUpdatesServer = grpc.ServerStreamingServer[CreatureSnapshotBatch]

// CreatureSync_ServiceDesc is the grpc.ServiceDesc for CreatureSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreatureSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.CreatureSync",
	HandlerType: (*CreatureSyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCreatureUpdates",
			Handler:       _CreatureSync_StreamCreatureUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service/grpc/creature.proto",
}
