// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: service/grpc/navmesh.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Snapshot de um polígono do NavMesh
type NavMeshSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GridX         int32                  `protobuf:"varint,2,opt,name=gridX,proto3" json:"gridX,omitempty"`
	GridZ         int32                  `protobuf:"varint,3,opt,name=gridZ,proto3" json:"gridZ,omitempty"`
	OffsetX       float32                `protobuf:"fixed32,4,opt,name=offsetX,proto3" json:"offsetX,omitempty"`
	OffsetZ       float32                `protobuf:"fixed32,5,opt,name=offsetZ,proto3" json:"offsetZ,omitempty"`
	Y             float32                `protobuf:"fixed32,6,opt,name=y,proto3" json:"y,omitempty"`
	Slope         float32                `protobuf:"fixed32,7,opt,name=slope,proto3" json:"slope,omitempty"`
	AreaType      string                 `protobuf:"bytes,8,opt,name=areaType,proto3" json:"areaType,omitempty"`
	Neighbors     []int32                `protobuf:"varint,9,rep,packed,name=neighbors,proto3" json:"neighbors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavMeshSnapshot) Reset() {
	*x = NavMeshSnapshot{}
	mi := &file_service_grpc_navmesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavMeshSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavMeshSnapshot) ProtoMessage() {}

func (x *NavMeshSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_service_grpc_navmesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavMeshSnapshot.ProtoReflect.Descriptor instead.
func (*NavMeshSnapshot) Descriptor() ([]byte, []int) {
	return file_service_grpc_navmesh_proto_rawDescGZIP(), []int{0}
}

func (x *NavMeshSnapshot) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NavMeshSnapshot) GetGridX() int32 {
	if x != nil {
		return x.GridX
	}
	return 0
}

func (x *NavMeshSnapshot) GetGridZ() int32 {
	if x != nil {
		return x.GridZ
	}
	return 0
}

func (x *NavMeshSnapshot) GetOffsetX() float32 {
	if x != nil {
		return x.OffsetX
	}
	return 0
}

func (x *NavMeshSnapshot) GetOffsetZ() float32 {
	if x != nil {
		return x.OffsetZ
	}
	return 0
}

func (x *NavMeshSnapshot) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NavMeshSnapshot) GetSlope() float32 {
	if x != nil {
		return x.Slope
	}
	return 0
}

func (x *NavMeshSnapshot) GetAreaType() string {
	if x != nil {
		return x.AreaType
	}
	return ""
}

func (x *NavMeshSnapshot) GetNeighbors() []int32 {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

// Lote de snapshots enviados pelo servidor
type NavMeshSnapshotBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polygons      []*NavMeshSnapshot     `protobuf:"bytes,1,rep,name=polygons,proto3" json:"polygons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavMeshSnapshotBatch) Reset() {
	*x = NavMeshSnapshotBatch{}
	mi := &file_service_grpc_navmesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavMeshSnapshotBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavMeshSnapshotBatch) ProtoMessage() {}

func (x *NavMeshSnapshotBatch) ProtoReflect() protoreflect.Message {
	mi := &file_service_grpc_navmesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavMeshSnapshotBatch.ProtoReflect.Descriptor instead.
func (*NavMeshSnapshotBatch) Descriptor() ([]byte, []int) {
	return file_service_grpc_navmesh_proto_rawDescGZIP(), []int{1}
}

func (x *NavMeshSnapshotBatch) GetPolygons() []*NavMeshSnapshot {
	if x != nil {
		return x.Polygons
	}
	return nil
}

// Requisição (ainda vazia, pode ser estendida no futuro)
type NavMeshStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavMeshStreamRequest) Reset() {
	*x = NavMeshStreamRequest{}
	mi := &file_service_grpc_navmesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavMeshStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavMeshStreamRequest) ProtoMessage() {}

func (x *NavMeshStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_grpc_navmesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavMeshStreamRequest.ProtoReflect.Descriptor instead.
func (*NavMeshStreamRequest) Descriptor() ([]byte, []int) {
	return file_service_grpc_navmesh_proto_rawDescGZIP(), []int{2}
}

func (x *NavMeshStreamRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

var File_service_grpc_navmesh_proto protoreflect.FileDescriptor

const file_service_grpc_navmesh_proto_rawDesc = "" +
	"\n" +
	"\x1aservice/grpc/navmesh.proto\x12\x04grpc\"\xdf\x01\n" +
	"\x0fNavMeshSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05gridX\x18\x02 \x01(\x05R\x05gridX\x12\x14\n" +
	"\x05gridZ\x18\x03 \x01(\x05R\x05gridZ\x12\x18\n" +
	"\aoffsetX\x18\x04 \x01(\x02R\aoffsetX\x12\x18\n" +
	"\aoffsetZ\x18\x05 \x01(\x02R\aoffsetZ\x12\f\n" +
	"\x01y\x18\x06 \x01(\x02R\x01y\x12\x14\n" +
	"\x05slope\x18\a \x01(\x02R\x05slope\x12\x1a\n" +
	"\bareaType\x18\b \x01(\tR\bareaType\x12\x1c\n" +
	"\tneighbors\x18\t \x03(\x05R\tneighbors\"I\n" +
	"\x14NavMeshSnapshotBatch\x121\n" +
	"\bpolygons\x18\x01 \x03(\v2\x15.grpc.NavMeshSnapshotR\bpolygons\"*\n" +
	"\x14NavMeshStreamRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone2b\n" +
	"\x0eNavMeshService\x12P\n" +
	"\x14StreamNavMeshUpdates\x12\x1a.grpc.NavMeshStreamRequest\x1a\x1a.grpc.NavMeshSnapshotBatch0\x01B0Z.github.com/lunajones/apeiron/service/grpc;grpcb\x06proto3"

var (
	file_service_grpc_navmesh_proto_rawDescOnce sync.Once
	file_service_grpc_navmesh_proto_rawDescData []byte
)

func file_service_grpc_navmesh_proto_rawDescGZIP() []byte {
	file_service_grpc_navmesh_proto_rawDescOnce.Do(func() {
		file_service_grpc_navmesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_grpc_navmesh_proto_rawDesc), len(file_service_grpc_navmesh_proto_rawDesc)))
	})
	return file_service_grpc_navmesh_proto_rawDescData
}

var file_service_grpc_navmesh_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_grpc_navmesh_proto_goTypes = []any{
	(*NavMeshSnapshot)(nil),      // 0: grpc.NavMeshSnapshot
	(*NavMeshSnapshotBatch)(nil), // 1: grpc.NavMeshSnapshotBatch
	(*NavMeshStreamRequest)(nil), // 2: grpc.NavMeshStreamRequest
}
var file_service_grpc_navmesh_proto_depIdxs = []int32{
	0, // 0: grpc.NavMeshSnapshotBatch.polygons:type_name -> grpc.NavMeshSnapshot
	2, // 1: grpc.NavMeshService.StreamNavMeshUpdates:input_type -> grpc.NavMeshStreamRequest
	1, // 2: grpc.NavMeshService.StreamNavMeshUpdates:output_type -> grpc.NavMeshSnapshotBatch
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_grpc_navmesh_proto_init() }
func file_service_grpc_navmesh_proto_init() {
	if File_service_grpc_navmesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_grpc_navmesh_proto_rawDesc), len(file_service_grpc_navmesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_grpc_navmesh_proto_goTypes,
		DependencyIndexes: file_service_grpc_navmesh_proto_depIdxs,
		MessageInfos:      file_service_grpc_navmesh_proto_msgTypes,
	}.Build()
	File_service_grpc_navmesh_proto = out.File
	file_service_grpc_navmesh_proto_goTypes = nil
	file_service_grpc_navmesh_proto_depIdxs = nil
}
